// ResumeRadar skill dictionaries.
// Each hard skill: { name: display name, syn: [alternate spellings/abbreviations] }
// Matching is case-insensitive with word boundaries handled in app.js.

const HARD_SKILLS = [
  // ── Programming & software engineering ──
  { name: "JavaScript", syn: ["js", "ecmascript"] },
  { name: "TypeScript", syn: ["ts"] },
  { name: "Python", syn: [] },
  { name: "Java", syn: [] },
  { name: "C#", syn: ["c sharp", "csharp"] },
  { name: "C++", syn: ["cpp", "c plus plus"] },
  { name: "C", syn: [] },
  { name: "Go", syn: ["golang"] },
  { name: "Rust", syn: [] },
  { name: "Ruby", syn: ["ruby on rails", "rails"] },
  { name: "PHP", syn: [] },
  { name: "Swift", syn: [] },
  { name: "Kotlin", syn: [] },
  { name: "Scala", syn: [] },
  { name: "R", syn: [] },
  { name: "MATLAB", syn: [] },
  { name: "Perl", syn: [] },
  { name: "SQL", syn: [] },
  { name: "NoSQL", syn: [] },
  { name: "HTML", syn: ["html5"] },
  { name: "CSS", syn: ["css3"] },
  { name: "Sass", syn: ["scss"] },
  { name: "React", syn: ["react.js", "reactjs"] },
  { name: "Angular", syn: ["angularjs", "angular.js"] },
  { name: "Vue", syn: ["vue.js", "vuejs"] },
  { name: "Svelte", syn: ["sveltekit"] },
  { name: "Next.js", syn: ["nextjs", "next js"] },
  { name: "Node.js", syn: ["node", "nodejs", "node js"] },
  { name: "Express", syn: ["express.js", "expressjs"] },
  { name: "Django", syn: [] },
  { name: "Flask", syn: [] },
  { name: "FastAPI", syn: [] },
  { name: "Spring", syn: ["spring boot", "springboot"] },
  { name: ".NET", syn: ["dotnet", "asp.net", "dot net"] },
  { name: "Laravel", syn: [] },
  { name: "GraphQL", syn: [] },
  { name: "REST API", syn: ["rest", "restful", "rest apis", "api development"] },
  { name: "Microservices", syn: ["micro services", "microservice"] },
  { name: "jQuery", syn: [] },
  { name: "Tailwind", syn: ["tailwindcss", "tailwind css"] },
  { name: "Bootstrap", syn: [] },
  { name: "Redux", syn: [] },
  { name: "WebSockets", syn: ["websocket"] },
  { name: "OAuth", syn: ["oauth2", "oauth 2.0"] },
  { name: "Unit testing", syn: ["unit tests"] },
  { name: "Test-driven development", syn: ["tdd", "test driven development"] },
  { name: "Jest", syn: [] },
  { name: "Cypress", syn: [] },
  { name: "Selenium", syn: [] },
  { name: "Playwright", syn: [] },
  { name: "Debugging", syn: [] },
  { name: "Code review", syn: ["code reviews"] },
  { name: "Object-oriented programming", syn: ["oop", "object oriented"] },
  { name: "Functional programming", syn: [] },
  { name: "Data structures", syn: [] },
  { name: "Algorithms", syn: [] },
  { name: "Distributed systems", syn: [] },
  { name: "System design", syn: ["systems design"] },
  { name: "Mobile development", syn: ["ios development", "android development"] },
  { name: "React Native", syn: [] },
  { name: "Flutter", syn: [] },
  { name: "Unity", syn: [] },
  { name: "Unreal Engine", syn: ["unreal"] },
  { name: "Embedded systems", syn: ["embedded software", "firmware"] },
  { name: "Shell scripting", syn: ["bash", "powershell", "shell"] },

  // ── Data, analytics & AI ──
  { name: "Machine learning", syn: ["ml"] },
  { name: "Deep learning", syn: [] },
  { name: "Artificial intelligence", syn: ["ai"] },
  { name: "Generative AI", syn: ["genai", "gen ai", "llm", "llms", "large language models"] },
  { name: "Prompt engineering", syn: [] },
  { name: "Natural language processing", syn: ["nlp"] },
  { name: "Computer vision", syn: [] },
  { name: "TensorFlow", syn: [] },
  { name: "PyTorch", syn: [] },
  { name: "scikit-learn", syn: ["sklearn", "scikit learn"] },
  { name: "Pandas", syn: [] },
  { name: "NumPy", syn: [] },
  { name: "Data analysis", syn: ["data analytics"] },
  { name: "Data science", syn: [] },
  { name: "Data engineering", syn: [] },
  { name: "Data visualization", syn: ["data viz"] },
  { name: "Data modeling", syn: ["data modelling"] },
  { name: "Data warehousing", syn: ["data warehouse"] },
  { name: "Data pipelines", syn: ["data pipeline", "etl", "elt"] },
  { name: "Big data", syn: [] },
  { name: "Statistics", syn: ["statistical analysis", "statistical modeling"] },
  { name: "A/B testing", syn: ["ab testing", "split testing", "experimentation"] },
  { name: "Tableau", syn: [] },
  { name: "Power BI", syn: ["powerbi"] },
  { name: "Looker", syn: ["looker studio", "google data studio"] },
  { name: "Excel", syn: ["microsoft excel", "ms excel", "advanced excel"] },
  { name: "Google Sheets", syn: [] },
  { name: "Pivot tables", syn: ["pivot table"] },
  { name: "VLOOKUP", syn: ["xlookup"] },
  { name: "Spark", syn: ["apache spark", "pyspark"] },
  { name: "Hadoop", syn: [] },
  { name: "Kafka", syn: ["apache kafka"] },
  { name: "Airflow", syn: ["apache airflow"] },
  { name: "dbt", syn: [] },
  { name: "Snowflake", syn: [] },
  { name: "Databricks", syn: [] },
  { name: "BigQuery", syn: ["big query"] },
  { name: "Redshift", syn: [] },
  { name: "PostgreSQL", syn: ["postgres"] },
  { name: "MySQL", syn: [] },
  { name: "SQL Server", syn: ["mssql", "microsoft sql server", "t-sql"] },
  { name: "MongoDB", syn: ["mongo"] },
  { name: "Redis", syn: [] },
  { name: "Elasticsearch", syn: ["elastic search"] },
  { name: "Oracle", syn: ["oracle database", "pl/sql"] },
  { name: "DynamoDB", syn: [] },
  { name: "Reporting", syn: ["reports", "dashboards", "dashboarding"] },
  { name: "Forecasting", syn: ["forecasts"] },
  { name: "KPI tracking", syn: ["kpis", "kpi"] },

  // ── Cloud, DevOps & IT ──
  { name: "AWS", syn: ["amazon web services"] },
  { name: "Azure", syn: ["microsoft azure"] },
  { name: "Google Cloud", syn: ["gcp", "google cloud platform"] },
  { name: "Docker", syn: ["containers", "containerization"] },
  { name: "Kubernetes", syn: ["k8s"] },
  { name: "Terraform", syn: [] },
  { name: "Ansible", syn: [] },
  { name: "Jenkins", syn: [] },
  { name: "CI/CD", syn: ["continuous integration", "continuous delivery", "continuous deployment", "ci cd"] },
  { name: "Git", syn: ["github", "gitlab", "bitbucket", "version control"] },
  { name: "Linux", syn: ["unix"] },
  { name: "Windows Server", syn: [] },
  { name: "Active Directory", syn: [] },
  { name: "Networking", syn: ["tcp/ip", "dns", "vpn", "network administration"] },
  { name: "Cybersecurity", syn: ["information security", "infosec", "it security", "security"] },
  { name: "Penetration testing", syn: ["pen testing", "pentesting"] },
  { name: "Vulnerability management", syn: ["vulnerability assessment"] },
  { name: "SIEM", syn: ["splunk", "sentinel"] },
  { name: "SOC 2", syn: ["soc2"] },
  { name: "ISO 27001", syn: [] },
  { name: "NIST", syn: [] },
  { name: "GDPR", syn: [] },
  { name: "HIPAA", syn: [] },
  { name: "Identity and access management", syn: ["iam"] },
  { name: "Incident response", syn: ["incident management"] },
  { name: "Monitoring", syn: ["observability", "datadog", "grafana", "prometheus", "new relic"] },
  { name: "Serverless", syn: ["lambda", "aws lambda", "cloud functions"] },
  { name: "Infrastructure as code", syn: ["iac"] },
  { name: "DevOps", syn: [] },
  { name: "Site reliability engineering", syn: ["sre"] },
  { name: "Technical support", syn: ["help desk", "helpdesk", "it support", "desktop support"] },
  { name: "Troubleshooting", syn: [] },
  { name: "ServiceNow", syn: [] },
  { name: "Jira", syn: [] },
  { name: "Confluence", syn: [] },
  { name: "SaaS", syn: ["software as a service"] },
  { name: "VMware", syn: ["virtualization"] },
  { name: "Office 365", syn: ["microsoft 365", "o365", "ms office", "microsoft office"] },
  { name: "SharePoint", syn: [] },
  { name: "macOS", syn: ["mac os"] },

  // ── Product & project management ──
  { name: "Project management", syn: [] },
  { name: "Product management", syn: [] },
  { name: "Agile", syn: ["agile methodologies", "agile methodology"] },
  { name: "Scrum", syn: ["scrum master"] },
  { name: "Kanban", syn: [] },
  { name: "Waterfall", syn: [] },
  { name: "Sprint planning", syn: ["sprints"] },
  { name: "Product roadmap", syn: ["roadmap", "roadmapping", "product roadmaps"] },
  { name: "Backlog management", syn: ["backlog grooming", "backlog refinement"] },
  { name: "User stories", syn: ["user story"] },
  { name: "Requirements gathering", syn: ["business requirements", "requirements analysis"] },
  { name: "Stakeholder management", syn: ["stakeholder engagement", "stakeholder communication"] },
  { name: "Risk management", syn: ["risk assessment", "risk mitigation"] },
  { name: "Budget management", syn: ["budgeting", "budget planning", "cost control"] },
  { name: "Resource allocation", syn: ["resource management", "resource planning"] },
  { name: "PMP", syn: ["pmp certification", "pmp certified"] },
  { name: "Six Sigma", syn: ["lean six sigma", "six sigma green belt", "six sigma black belt"] },
  { name: "Lean", syn: ["lean manufacturing", "lean methodology"] },
  { name: "Process improvement", syn: ["process optimization", "continuous improvement"] },
  { name: "Change management", syn: [] },
  { name: "Vendor management", syn: ["vendor relations", "supplier management"] },
  { name: "Cross-functional teams", syn: ["cross functional", "cross-functional collaboration", "cross-functional"] },
  { name: "Product lifecycle", syn: ["product life cycle", "product development lifecycle", "sdlc"] },
  { name: "Go-to-market", syn: ["gtm", "go to market", "product launch", "product launches"] },
  { name: "OKRs", syn: ["okr", "objectives and key results"] },
  { name: "Roadmap prioritization", syn: ["prioritization frameworks", "rice", "moscow"] },
  { name: "Asana", syn: [] },
  { name: "Trello", syn: [] },
  { name: "Monday.com", syn: [] },
  { name: "Smartsheet", syn: [] },
  { name: "MS Project", syn: ["microsoft project"] },
  { name: "Gantt charts", syn: ["gantt"] },
  { name: "User research", syn: ["customer research"] },
  { name: "Market research", syn: ["market analysis", "competitive analysis", "competitor analysis"] },
  { name: "Product analytics", syn: ["amplitude", "mixpanel", "product metrics"] },

  // ── Marketing, content & social ──
  { name: "Digital marketing", syn: ["online marketing"] },
  { name: "SEO", syn: ["search engine optimization"] },
  { name: "SEM", syn: ["search engine marketing", "paid search", "ppc", "pay per click"] },
  { name: "Google Ads", syn: ["adwords", "google adwords"] },
  { name: "Meta Ads", syn: ["facebook ads", "instagram ads"] },
  { name: "Social media marketing", syn: ["social media management", "social media strategy", "smm"] },
  { name: "Content marketing", syn: ["content strategy", "content creation"] },
  { name: "Copywriting", syn: ["copy writing", "ad copy"] },
  { name: "Email marketing", syn: ["email campaigns", "newsletters"] },
  { name: "Marketing automation", syn: ["hubspot", "marketo", "mailchimp", "klaviyo", "pardot"] },
  { name: "CRM", syn: ["customer relationship management"] },
  { name: "Salesforce", syn: ["sfdc"] },
  { name: "Google Analytics", syn: ["ga4"] },
  { name: "Conversion rate optimization", syn: ["cro", "conversion optimization"] },
  { name: "Brand management", syn: ["branding", "brand strategy"] },
  { name: "Public relations", syn: ["pr", "media relations"] },
  { name: "Influencer marketing", syn: ["influencer partnerships"] },
  { name: "Affiliate marketing", syn: [] },
  { name: "Growth marketing", syn: ["growth hacking", "demand generation", "demand gen"] },
  { name: "Lead generation", syn: ["lead gen", "lead nurturing"] },
  { name: "Campaign management", syn: ["marketing campaigns", "campaign planning"] },
  { name: "Video editing", syn: ["premiere pro", "final cut", "davinci resolve", "video production"] },
  { name: "Photography", syn: ["photo editing"] },
  { name: "Canva", syn: [] },
  { name: "TikTok", syn: [] },
  { name: "YouTube", syn: [] },
  { name: "LinkedIn", syn: [] },
  { name: "Community management", syn: ["community building", "discord moderation"] },
  { name: "E-commerce", syn: ["ecommerce", "shopify", "woocommerce", "amazon fba"] },
  { name: "Merchandising", syn: ["visual merchandising"] },

  // ── Sales & customer success ──
  { name: "Sales", syn: ["selling"] },
  { name: "B2B sales", syn: ["b2b"] },
  { name: "B2C sales", syn: ["b2c"] },
  { name: "Inside sales", syn: [] },
  { name: "Outside sales", syn: ["field sales"] },
  { name: "Cold calling", syn: ["cold outreach", "prospecting", "cold emailing"] },
  { name: "Account management", syn: ["account executive", "key accounts"] },
  { name: "Business development", syn: ["bd", "partnerships"] },
  { name: "Pipeline management", syn: ["sales pipeline", "pipeline development"] },
  { name: "Quota attainment", syn: ["quota", "sales targets", "sales goals"] },
  { name: "Negotiation", syn: ["contract negotiation", "negotiating"] },
  { name: "Closing", syn: ["deal closing", "closing deals"] },
  { name: "Customer success", syn: ["client success"] },
  { name: "Customer service", syn: ["customer support", "client service", "customer care"] },
  { name: "Customer retention", syn: ["churn reduction", "renewals"] },
  { name: "Upselling", syn: ["cross-selling", "upsell", "cross sell"] },
  { name: "Sales enablement", syn: [] },
  { name: "HubSpot", syn: [] },
  { name: "Outreach", syn: ["salesloft"] },
  { name: "Point of sale", syn: ["pos", "pos systems"] },
  { name: "Relationship building", syn: ["client relationships", "customer relationships", "relationship management"] },

  // ── Finance & accounting ──
  { name: "Accounting", syn: [] },
  { name: "Bookkeeping", syn: [] },
  { name: "Accounts payable", syn: ["ap"] },
  { name: "Accounts receivable", syn: ["ar"] },
  { name: "Financial analysis", syn: ["financial analytics"] },
  { name: "Financial modeling", syn: ["financial models", "financial modelling"] },
  { name: "Financial reporting", syn: ["financial statements"] },
  { name: "Financial planning", syn: ["fp&a", "fpa"] },
  { name: "Forecasting and budgeting", syn: ["budget forecasting"] },
  { name: "GAAP", syn: ["us gaap"] },
  { name: "IFRS", syn: [] },
  { name: "Auditing", syn: ["internal audit", "external audit", "audits"] },
  { name: "Tax preparation", syn: ["tax returns", "taxation", "tax compliance"] },
  { name: "Payroll", syn: ["payroll processing"] },
  { name: "QuickBooks", syn: ["quick books"] },
  { name: "SAP", syn: [] },
  { name: "NetSuite", syn: [] },
  { name: "Oracle ERP", syn: ["erp"] },
  { name: "Reconciliation", syn: ["account reconciliation", "bank reconciliation"] },
  { name: "General ledger", syn: ["gl"] },
  { name: "Month-end close", syn: ["month end close", "closing process"] },
  { name: "CPA", syn: ["certified public accountant"] },
  { name: "CFA", syn: [] },
  { name: "Valuation", syn: ["dcf", "discounted cash flow"] },
  { name: "Investment analysis", syn: ["portfolio management", "asset management"] },
  { name: "Underwriting", syn: [] },
  { name: "Credit analysis", syn: ["credit risk"] },
  { name: "Anti-money laundering", syn: ["aml", "kyc", "know your customer"] },
  { name: "Variance analysis", syn: [] },
  { name: "Cost accounting", syn: ["cost analysis"] },

  // ── Healthcare ──
  { name: "Patient care", syn: ["patient-centered care", "direct patient care"] },
  { name: "Electronic health records", syn: ["ehr", "emr", "electronic medical records"] },
  { name: "Epic", syn: ["epic systems"] },
  { name: "Cerner", syn: [] },
  { name: "Medical terminology", syn: [] },
  { name: "Vital signs", syn: [] },
  { name: "Phlebotomy", syn: [] },
  { name: "Medication administration", syn: ["med administration"] },
  { name: "CPR", syn: ["bls", "basic life support"] },
  { name: "ACLS", syn: ["advanced cardiac life support"] },
  { name: "Triage", syn: [] },
  { name: "Care planning", syn: ["care plans", "treatment plans"] },
  { name: "Charting", syn: ["clinical documentation"] },
  { name: "ICD-10", syn: ["icd10", "medical coding", "cpt coding"] },
  { name: "Medical billing", syn: ["insurance billing", "claims processing"] },
  { name: "Telehealth", syn: ["telemedicine"] },
  { name: "Infection control", syn: [] },
  { name: "Case management", syn: [] },
  { name: "Clinical research", syn: ["clinical trials"] },
  { name: "Registered nurse", syn: ["rn"] },
  { name: "Certified nursing assistant", syn: ["cna"] },

  // ── Design & creative ──
  { name: "Graphic design", syn: ["visual design"] },
  { name: "UI design", syn: ["user interface design", "ui"] },
  { name: "UX design", syn: ["user experience", "ux"] },
  { name: "UX research", syn: ["usability testing", "user testing"] },
  { name: "Figma", syn: [] },
  { name: "Sketch", syn: [] },
  { name: "Adobe Photoshop", syn: ["photoshop"] },
  { name: "Adobe Illustrator", syn: ["illustrator"] },
  { name: "Adobe InDesign", syn: ["indesign"] },
  { name: "Adobe XD", syn: [] },
  { name: "After Effects", syn: ["adobe after effects"] },
  { name: "Adobe Creative Suite", syn: ["creative cloud", "adobe creative cloud"] },
  { name: "Wireframing", syn: ["wireframes"] },
  { name: "Prototyping", syn: ["prototypes"] },
  { name: "Design systems", syn: ["design system"] },
  { name: "Typography", syn: [] },
  { name: "Motion graphics", syn: ["animation"] },
  { name: "3D modeling", syn: ["blender", "3ds max", "maya"] },
  { name: "CAD", syn: ["autocad", "solidworks", "revit"] },
  { name: "Accessibility", syn: ["wcag", "a11y", "ada compliance"] },

  // ── HR, admin & operations ──
  { name: "Recruiting", syn: ["recruitment", "talent acquisition", "sourcing candidates"] },
  { name: "Onboarding", syn: ["new hire onboarding", "employee onboarding"] },
  { name: "Employee relations", syn: [] },
  { name: "Performance management", syn: ["performance reviews"] },
  { name: "HRIS", syn: ["workday", "bamboohr", "adp"] },
  { name: "Benefits administration", syn: ["benefits"] },
  { name: "Compensation", syn: ["comp and benefits", "total rewards"] },
  { name: "Training and development", syn: ["employee training", "learning and development", "l&d"] },
  { name: "Compliance", syn: ["regulatory compliance"] },
  { name: "Labor laws", syn: ["employment law", "flsa", "eeo"] },
  { name: "Scheduling", syn: ["calendar management", "appointment scheduling"] },
  { name: "Data entry", syn: [] },
  { name: "Office administration", syn: ["office management", "administrative support"] },
  { name: "Travel coordination", syn: ["travel arrangements"] },
  { name: "Event planning", syn: ["event coordination", "event management"] },
  { name: "Inventory management", syn: ["inventory control", "stock management"] },
  { name: "Supply chain", syn: ["supply chain management", "scm"] },
  { name: "Logistics", syn: ["logistics coordination"] },
  { name: "Procurement", syn: ["purchasing", "sourcing"] },
  { name: "Warehouse operations", syn: ["warehousing", "shipping and receiving"] },
  { name: "Forklift operation", syn: ["forklift certified", "forklift"] },
  { name: "Quality assurance", syn: ["qa", "quality control", "qc"] },
  { name: "OSHA", syn: ["osha compliance", "workplace safety", "safety compliance"] },
  { name: "Fleet management", syn: [] },
  { name: "Route planning", syn: ["route optimization"] },
  { name: "Food safety", syn: ["servsafe", "haccp"] },
  { name: "Cash handling", syn: ["cash management"] },
  { name: "Loss prevention", syn: [] },

  // ── Legal, education & misc professional ──
  { name: "Legal research", syn: ["westlaw", "lexisnexis"] },
  { name: "Contract drafting", syn: ["contract review", "contract management"] },
  { name: "Litigation", syn: ["litigation support"] },
  { name: "Paralegal", syn: [] },
  { name: "Due diligence", syn: [] },
  { name: "Intellectual property", syn: ["ip", "trademarks", "patents"] },
  { name: "Curriculum development", syn: ["lesson planning", "curriculum design"] },
  { name: "Classroom management", syn: [] },
  { name: "Special education", syn: ["iep", "sped"] },
  { name: "ESL", syn: ["esol", "tefl", "tesol"] },
  { name: "Tutoring", syn: [] },
  { name: "Grant writing", syn: ["grants", "grant management"] },
  { name: "Fundraising", syn: ["donor relations", "development"] },
  { name: "Technical writing", syn: ["documentation", "technical documentation"] },
  { name: "Editing", syn: ["proofreading", "copy editing"] },
  { name: "Translation", syn: ["interpretation", "bilingual"] },
  { name: "Spanish", syn: [] },
  { name: "French", syn: [] },
  { name: "Mandarin", syn: ["chinese"] },
  { name: "German", syn: [] },
];

const SOFT_SKILLS = [
  { name: "Communication", syn: ["communication skills", "verbal communication", "written communication", "verbal and written"] },
  { name: "Leadership", syn: ["leading teams", "team leadership", "people leadership"] },
  { name: "Teamwork", syn: ["team player", "collaboration", "collaborative", "working in a team"] },
  { name: "Problem solving", syn: ["problem-solving", "problem solver"] },
  { name: "Time management", syn: ["managing time", "meeting deadlines", "deadline-driven"] },
  { name: "Adaptability", syn: ["adaptable", "flexibility", "flexible"] },
  { name: "Attention to detail", syn: ["detail-oriented", "detail oriented", "meticulous"] },
  { name: "Critical thinking", syn: ["analytical thinking", "analytical skills", "analytical"] },
  { name: "Creativity", syn: ["creative thinking", "creative"] },
  { name: "Organization", syn: ["organizational skills", "organized", "organisational"] },
  { name: "Multitasking", syn: ["multi-tasking", "juggling priorities"] },
  { name: "Conflict resolution", syn: ["resolving conflicts", "de-escalation"] },
  { name: "Mentoring", syn: ["mentorship", "coaching"] },
  { name: "Public speaking", syn: ["presentations", "presentation skills", "presenting"] },
  { name: "Decision making", syn: ["decision-making", "sound judgment"] },
  { name: "Emotional intelligence", syn: ["empathy", "eq"] },
  { name: "Initiative", syn: ["self-starter", "self starter", "proactive"] },
  { name: "Work ethic", syn: ["hardworking", "dependable", "reliable", "reliability"] },
  { name: "Interpersonal skills", syn: ["people skills", "interpersonal"] },
  { name: "Strategic thinking", syn: ["strategic planning", "strategy", "strategic"] },
  { name: "Prioritization", syn: ["prioritizing", "prioritize"] },
  { name: "Customer focus", syn: ["customer-focused", "client-focused", "customer-centric", "customer orientation"] },
  { name: "Independence", syn: ["work independently", "working independently", "self-directed", "autonomous", "autonomy"] },
  { name: "Fast-paced environment", syn: ["fast paced", "fast-paced", "dynamic environment"] },
  { name: "Curiosity", syn: ["eager to learn", "willingness to learn", "growth mindset", "continuous learning"] },
  { name: "Accountability", syn: ["ownership", "taking ownership", "accountable"] },
  { name: "Patience", syn: [] },
  { name: "Active listening", syn: ["listening skills"] },
  { name: "Persuasion", syn: ["influencing", "influence"] },
  { name: "Team building", syn: ["building teams"] },
];

// Strong action verbs we look for at the start of resume lines.
const ACTION_VERBS = [
  "led", "managed", "built", "created", "developed", "designed", "launched",
  "implemented", "improved", "increased", "reduced", "delivered", "achieved",
  "drove", "spearheaded", "coordinated", "streamlined", "negotiated", "mentored",
  "trained", "analyzed", "optimized", "automated", "established", "generated",
  "secured", "resolved", "executed", "oversaw", "transformed", "directed",
  "produced", "initiated", "founded", "engineered", "architected", "authored",
  "accelerated", "boosted", "consolidated", "cut", "decreased", "doubled",
  "eliminated", "exceeded", "expanded", "grew", "maximized", "minimized",
  "saved", "surpassed", "owned", "shipped", "scaled", "supervised", "facilitated",
  "championed", "pioneered", "revamped", "redesigned", "restructured", "modernized",
  "migrated", "deployed", "integrated", "standardized", "audited", "forecasted",
  "budgeted", "recruited", "hired", "onboarded", "presented", "published",
  "researched", "tested", "validated", "collaborated", "partnered", "advised",
  "guided", "taught", "organized", "planned", "processed", "maintained",
];

// Vague clichés that weaken a resume — better replaced with concrete examples.
const CLICHES = [
  "team player", "hard worker", "go-getter", "go getter", "think outside the box",
  "thinks outside the box", "outside the box", "thought leader", "synergy",
  "guru", "ninja", "rockstar", "rock star", "results-driven", "results driven",
  "go above and beyond", "goes above and beyond", "people person",
  "track record of success", "proven track record", "dynamic individual",
  "highly motivated individual", "works well under pressure", "best of breed",
  "win-win", "value-add", "move the needle", "wear many hats",
];

// Common English stopwords + job-posting boilerplate that should never count as keywords.
const STOPWORDS = new Set([
  // english stopwords
  "a","an","and","are","as","at","be","been","being","but","by","can","could",
  "did","do","does","doing","done","for","from","had","has","have","having",
  "he","her","here","hers","him","his","how","i","if","in","into","is","it",
  "its","just","me","more","most","my","no","nor","not","now","of","off","on",
  "once","only","or","other","our","ours","out","over","own","same","she",
  "should","so","some","such","than","that","the","their","theirs","them",
  "then","there","these","they","this","those","through","to","too","under",
  "until","up","very","was","we","were","what","when","where","which","while",
  "who","whom","why","will","with","would","you","your","yours","also","may",
  "must","shall","each","both","between","during","before","after","above",
  "below","again","further","about","against","all","any","because","etc",
  "via","per","within","without","across","among","upon","toward","towards",
  // job-posting boilerplate
  "job","role","position","candidate","candidates","applicant","applicants",
  "responsibilities","requirements","required","requirement","preferred",
  "qualification","qualifications","experience","experiences","years","year",
  "ability","able","skills","skill","strong","excellent","good","great",
  "knowledge","understanding","familiarity","familiar","proficiency",
  "proficient","including","include","includes","included","plus","bonus",
  "work","working","works","team","teams","company","organization","org",
  "employer","employee","employees","opportunity","opportunities","equal",
  "diversity","inclusive","inclusion","benefits","salary","compensation",
  "insurance","dental","vision","401k","pto","paid","vacation","holidays",
  "remote","hybrid","onsite","on-site","location","located","apply",
  "application","applications","please","join","looking","seek","seeking",
  "ideal","successful","duties","duty","perform","performs","performing",
  "assist","assists","assisting","support","supporting","related","relevant",
  "minimum","maximum","least","degree","bachelor","bachelors","master",
  "masters","phd","diploma","high","school","education","field","equivalent",
  "etc.","day","days","week","weekly","month","monthly","time","full-time",
  "part-time","full","part","environment","environments","various","other",
  "others","new","help","make","made","making","ensure","ensures","ensuring",
  "provide","provides","providing","using","use","used","uses","need","needs",
  "needed","want","wants","like","well","based","level","levels","areas",
  "area","things","thing","etc…","status","race","religion","gender","sexual",
  "orientation","national","origin","veteran","disability","applicable","law",
  "laws","employment","hire","hiring","hired","contact","email","phone",
  "click","submit","resume","cv","cover","letter","u.s.","us","eligible",
  "eligibility","authorization","authorized","sponsorship","visa","title",
  "department","reports","reporting","manager","director","mission","values",
  "culture","passionate","passion","exciting","fun","amazing","world-class",
  "industry","industries","leading","leader","fast-growing","growing","grow",
  "one","two","three","four","five","get","take","takes","go","every","daily",
  "regular","regularly","general","specific","additional","etc,","who",
  // generic JD verbs/adjectives that add noise as keywords
  "build","building","builds","develop","developing","develops","manage",
  "managing","manages","own","owning","owns","drive","driving","drives",
  "deliver","delivering","delivers","create","creating","creates","lead",
  "leading","leads","comfortable","similar","monthly","quarterly","annual",
  "annually","effectively","efficiently","successfully","demonstrated",
  "proven","hands-on","willing","willingness","desire","desired","highly",
  "responsible","maintain","maintaining","maintains","execute","executing",
  "partner","partnering","collaborate","collaborating","closely","across",
]);
